#*********************************************************************#
#*  Name: Tommy Franczak                                             *#
#*  Assignment 4                                                     *#
#*  Date: October 12th, 2018                                         *#
#*                                                                   *#
#*  File: makefile                                                   *#
#*  Purpose: make the executable for assignment 4                    *#
#*                                                                   *#
#*********************************************************************#

Assign4: Assign4.cc Process.cc
	g++ -o Assign4 Assign4.cc Process.cc -I.

clean:
	rm Assign4
